-- ===============================================
-- Smart Farm Crop Health Monitor - Tables Script
-- Author: HIRWA Roy (ID: 24174)
-- ===============================================

-- =========================
-- 1. Farms Table
-- =========================
CREATE TABLE farms (
    farm_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    farm_name     VARCHAR2(100) NOT NULL,
    location      VARCHAR2(200),
    owner_name    VARCHAR2(100),
    created_at    DATE DEFAULT SYSDATE
);

-- =========================
-- 2. Crops Table
-- =========================
CREATE TABLE crops (
    crop_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    farm_id       NUMBER NOT NULL,
    crop_name     VARCHAR2(100) NOT NULL,
    plant_date    DATE,
    harvest_date  DATE,
    FOREIGN KEY (farm_id) REFERENCES farms(farm_id)
);

-- =========================
-- 3. Sensors Table
-- =========================
CREATE TABLE sensors (
    sensor_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    farm_id       NUMBER NOT NULL,
    sensor_type   VARCHAR2(50) NOT NULL, -- e.g., Temperature, Moisture, pH
    installed_at  DATE DEFAULT SYSDATE,
    FOREIGN KEY (farm_id) REFERENCES farms(farm_id)
);

-- =========================
-- 4. Crop Health Readings Table
-- =========================
CREATE TABLE crop_health_readings (
    reading_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    crop_id        NUMBER NOT NULL,
    sensor_id      NUMBER NOT NULL,
    reading_value  NUMBER(10,2) NOT NULL,
    reading_date   DATE DEFAULT SYSDATE,
    FOREIGN KEY (crop_id) REFERENCES crops(crop_id),
    FOREIGN KEY (sensor_id) REFERENCES sensors(sensor_id)
);

-- =========================
-- 5. Alerts Table
-- =========================
CREATE TABLE alerts (
    alert_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    crop_id        NUMBER NOT NULL,
    sensor_id      NUMBER NOT NULL,
    alert_type     VARCHAR2(50) NOT NULL, -- e.g., Low Moisture, High Temperature
    alert_message  VARCHAR2(255),
    alert_date     DATE DEFAULT SYSDATE,
    status         VARCHAR2(20) DEFAULT 'Pending', -- Pending, Resolved
    FOREIGN KEY (crop_id) REFERENCES crops(crop_id),
    FOREIGN KEY (sensor_id) REFERENCES sensors(sensor_id)
);

