-- ===============================================
-- Smart Farm Crop Health Monitor - Tables Script
-- Author: HIRWA Roy (ID: 24174)
-- ===============================================

-- ===============================================
-- Smart Farm Crop Health Monitor - Tables Script
-- ===============================================

-- =========================
-- 1. Farms Table
-- =========================
CREATE TABLE farms (
    farm_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    farm_name VARCHAR2(100) NOT NULL,
    location  VARCHAR2(200)
);

-- =========================
-- 2. Crops Table
-- =========================
CREATE TABLE crops (
    crop_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    farm_id     NUMBER NOT NULL,
    crop_name   VARCHAR2(100) NOT NULL,
    planting_date DATE,
    FOREIGN KEY (farm_id) REFERENCES farms(farm_id)
);

-- =========================
-- 3. Sensors Table
-- =========================
CREATE TABLE sensors (
    sensor_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sensor_type VARCHAR2(50) NOT NULL, -- e.g., Moisture, Temperature
    location    VARCHAR2(100)
);

-- =========================
-- 4. Alerts Table
-- =========================
CREATE TABLE alerts (
    alert_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    crop_id        NUMBER NOT NULL,
    sensor_id      NUMBER NOT NULL,
    alert_type     VARCHAR2(50) NOT NULL, -- e.g., Low Moisture, High Temperature
    alert_message  VARCHAR2(255),
    alert_date     DATE DEFAULT SYSDATE,
    status         VARCHAR2(20) DEFAULT 'Pending', -- Pending, Resolved
    FOREIGN KEY (crop_id) REFERENCES crops(crop_id),
    FOREIGN KEY (sensor_id) REFERENCES sensors(sensor_id)
);

-- =========================
-- 5. Optional: Sensor Readings Table
-- =========================
CREATE TABLE sensor_readings (
    reading_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sensor_id     NUMBER NOT NULL,
    reading_value NUMBER NOT NULL,
    reading_date  DATE DEFAULT SYSDATE,
    FOREIGN KEY (sensor_id) REFERENCES sensors(sensor_id)
);

