-- ============================================================================
-- SMART FARM CROP HEALTH MONITOR DATABASE
-- ============================================================================
-- Author: Hirwa Roy
-- Description: Database for monitoring farm, crops, sensors, and alerts
-- ============================================================================

-- ============================================================================
-- STEP 1: CREATE FARMERS TABLE (No Dependencies)
-- ============================================================================
CREATE TABLE Farmers (
    Farmer_ID NUMBER GENERATED BY DEFAULT AS IDENTITY 
        START WITH 1 INCREMENT BY 1 PRIMARY KEY,
    First_Name VARCHAR2(50) NOT NULL,
    Last_Name VARCHAR2(50) NOT NULL,
    Phone VARCHAR2(15) UNIQUE NOT NULL,
    Email VARCHAR2(100) UNIQUE,
    Address VARCHAR2(255),
    Join_Date DATE DEFAULT SYSDATE,
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_email_format CHECK (Email LIKE '%@%.%' OR Email IS NULL)
);

COMMIT;
PROMPT "Farmers table created successfully!";

-- ============================================================================
-- STEP 2: CREATE FARMS TABLE (Depends on Farmers)
-- ============================================================================
CREATE TABLE Farms (
    Farm_ID NUMBER GENERATED BY DEFAULT AS IDENTITY 
        START WITH 1 INCREMENT BY 1 PRIMARY KEY,
    Farmer_ID NUMBER NOT NULL,
    Farm_Name VARCHAR2(100) NOT NULL,
    Location VARCHAR2(100) NOT NULL,
    Size_Acres NUMBER(6,2) CHECK (Size_Acres > 0),
    Soil_Type VARCHAR2(50),
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_farm_farmer FOREIGN KEY (Farmer_ID)
        REFERENCES Farmers(Farmer_ID) ON DELETE CASCADE,
    CONSTRAINT uk_farm_name UNIQUE (Farm_Name, Farmer_ID)
);

COMMIT;
PROMPT "Farms table created successfully!";

-- ============================================================================
-- STEP 3: CREATE CROPS TABLE (Depends on Farms)
-- ============================================================================
CREATE TABLE Crops (
    Crop_ID NUMBER GENERATED BY DEFAULT AS IDENTITY 
        START WITH 1 INCREMENT BY 1 PRIMARY KEY,
    Farm_ID NUMBER NOT NULL,
    Crop_Name VARCHAR2(100) NOT NULL,
    Plant_Date DATE DEFAULT SYSDATE,
    Harvest_Date DATE,
    Crop_Status VARCHAR2(20) DEFAULT 'Healthy',
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_crop_farm FOREIGN KEY (Farm_ID)
        REFERENCES Farms(Farm_ID) ON DELETE CASCADE,
    CONSTRAINT chk_crop_status CHECK (Crop_Status IN ('Healthy', 'Diseased', 'Harvested', 'Dead'))
);

COMMIT;
PROMPT "Crops table created successfully!";

-- ============================================================================
-- STEP 4: CREATE SENSORS TABLE (Depends on Farms)
-- ============================================================================
CREATE TABLE Sensors (
    Sensor_ID NUMBER GENERATED BY DEFAULT AS IDENTITY 
        START WITH 1 INCREMENT BY 1 PRIMARY KEY,
    Farm_ID NUMBER NOT NULL,
    Sensor_Type VARCHAR2(50) NOT NULL,
    Installation_Date DATE DEFAULT SYSDATE,
    Status VARCHAR2(20) DEFAULT 'Active',
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sensor_farm FOREIGN KEY (Farm_ID)
        REFERENCES Farms(Farm_ID) ON DELETE CASCADE,
    CONSTRAINT chk_sensor_status CHECK (Status IN ('Active', 'Inactive', 'Maintenance'))
);

COMMIT;
PROMPT "Sensors table created successfully!";

-- ============================================================================
-- STEP 5: CREATE SENSOR_READINGS TABLE (Depends on Sensors and Crops)
-- ============================================================================
CREATE TABLE Sensor_Readings (
    Reading_ID NUMBER GENERATED BY DEFAULT AS IDENTITY 
        START WITH 1 INCREMENT BY 1 PRIMARY KEY,
    Sensor_ID NUMBER NOT NULL,
    Crop_ID NUMBER,
    Reading_Time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Temperature NUMBER(5,2),
    Humidity NUMBER(5,2),
    Soil_Moisture NUMBER(5,2),
    Health_Index NUMBER(5,2),
    CONSTRAINT fk_read_sensor FOREIGN KEY (Sensor_ID)
        REFERENCES Sensors(Sensor_ID) ON DELETE CASCADE,
    CONSTRAINT fk_read_crop FOREIGN KEY (Crop_ID)
        REFERENCES Crops(Crop_ID) ON DELETE SET NULL,
    CONSTRAINT chk_values_positive CHECK (Temperature >= 0 AND Humidity >= 0 AND Soil_Moisture >= 0)
);

COMMIT;
PROMPT "Sensor_Readings table created successfully!";

-- ============================================================================
-- STEP 6: CREATE ALERTS TABLE (Depends on Crops)
-- ============================================================================
CREATE TABLE Alerts (
    Alert_ID NUMBER GENERATED BY DEFAULT AS IDENTITY 
        START WITH 1 INCREMENT BY 1 PRIMARY KEY,
    Crop_ID NUMBER NOT NULL,
    Alert_Type VARCHAR2(100) NOT NULL,
    Alert_Message VARCHAR2(255),
    Severity VARCHAR2(10) DEFAULT 'Low',
    Alert_Date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_alert_crop FOREIGN KEY (Crop_ID)
        REFERENCES Crops(Crop_ID) ON DELETE CASCADE,
    CONSTRAINT chk_severity CHECK (Severity IN ('Low', 'Medium', 'High', 'Critical'))
);

COMMIT;
PROMPT "Alerts table created successfully!";

-- ============================================================================
-- STEP 7: CREATE PEST_CONTROL TABLE (Depends on Crops)
-- ============================================================================
CREATE TABLE Pest_Control (
    Pest_ID NUMBER GENERATED BY DEFAULT AS IDENTITY 
        START WITH 1 INCREMENT BY 1 PRIMARY KEY,
    Crop_ID NUMBER NOT NULL,
    Pesticide_Name VARCHAR2(100),
    Application_Date DATE DEFAULT SYSDATE,
    Notes VARCHAR2(255),
    CONSTRAINT fk_pest_crop FOREIGN KEY (Crop_ID)
        REFERENCES Crops(Crop_ID) ON DELETE CASCADE
);

COMMIT;
PROMPT "Pest_Control table created successfully!";

-- ============================================================================
-- STEP 8: CREATE WEATHER_LOGS TABLE (Depends on Farms)
-- ============================================================================
CREATE TABLE Weather_Logs (
    Weather_ID NUMBER GENERATED BY DEFAULT AS IDENTITY 
        START WITH 1 INCREMENT BY 1 PRIMARY KEY,
    Farm_ID NUMBER NOT NULL,
    Log_Date DATE DEFAULT SYSDATE,
    Temperature NUMBER(5,2),
    Humidity NUMBER(5,2),
    Rainfall NUMBER(6,2),
    Wind_Speed NUMBER(6,2),
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_weather_farm FOREIGN KEY (Farm_ID)
        REFERENCES Farms(Farm_ID) ON DELETE CASCADE
);

COMMIT;
PROMPT "Weather_Logs table created successfully!";

-- ============================================================================
-- STEP 9: CREATE PRODUCTIVITY_REPORT TABLE (Depends on Crops)
-- ============================================================================
CREATE TABLE Productivity_Report (
    Report_ID NUMBER GENERATED BY DEFAULT AS IDENTITY 
        START WITH 1 INCREMENT BY 1 PRIMARY KEY,
    Crop_ID NUMBER NOT NULL,
    Yield_Amount NUMBER(10,2),
    Harvest_Date DATE,
    Report_Date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Comments VARCHAR2(255),
    CONSTRAINT fk_prod_crop FOREIGN KEY (Crop_ID)
        REFERENCES Crops(Crop_ID) ON DELETE CASCADE,
    CONSTRAINT chk_yield_positive CHECK (Yield_Amount >= 0)
);

COMMIT;
PROMPT "Productivity_Report table created successfully!";

-- ============================================================================
-- VERIFICATION QUERY
-- ============================================================================
PROMPT "=== VERIFYING SMART FARM TABLES ===";
SELECT table_name FROM user_tables
WHERE table_name IN ('FARMERS', 'FARMS', 'CROPS', 'SENSORS', 'SENSOR_READINGS',
                     'ALERTS', 'PEST_CONTROL', 'WEATHER_LOGS', 'PRODUCTIVITY_REPORT')
ORDER BY table_name;

PROMPT "=== SMART FARM DATABASE CREATED SUCCESSFULLY! ===";
